services:
  mongo:
    image: mongo:7
    container_name: mongo
    networks:
      - backend
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: pass
      MONGO_INITDB_DATABASE: mydbmongo
    ports:
      - "27017:27017"
    
    command: ["mongod", "--quiet"]
    logging:
      driver: "none"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh mongo:27017/mydbmongo --quiet
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: backend:latest
    container_name: backend_mongo_redis
    ports:
      - "3001:3000"
    networks:
      - backend
    environment:
      APP_PORT: 3001
      DATABASE_TYPE: mongodb
      DATABASE_HOST: mongo
      DATABASE_PORT: 27017
      DATABASE_NAME: mydbmongo
      DATABASE_USERNAME: mongo
      DATABASE_PASSWORD: pass
    depends_on:
      mongo:
        condition: service_healthy

networks:
  backend:
    driver: bridge

volumes:
  backend-node-modules: {}
  mongo_data: {}